spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

      routes:
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: alert-service-route
          uri: lb://ALERT-SERVICE
          predicates:
            - Path=/ingest/**

        - id: context-dashboard-route
          uri: lb://CONTEXT-SERVICE
          predicates:
            - Path=/context/**

        - id: context-config-route
          uri: lb://CONTEXT-SERVICE
          predicates:
            - Path=/api/config/**

        - id: jira-service-route
          uri: lb://JIRA-SERVICE
          predicates:
            - Path=/api/jira/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true

  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [traceId=%X{traceId},spanId=%X{spanId}]"

  level:
    root: INFO
    com.incidentbbrain.alertservice: INFO
    org.springframework.web: INFO