spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

      routes:
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: alert-service-route
          uri: lb://ALERT-SERVICE
          predicates:
            - Path=/ingest/**

        - id: context-dashboard-route
          uri: lb://CONTEXT-SERVICE
          predicates:
            - Path=/context/**

        - id: context-config-route
          uri: lb://CONTEXT-SERVICE
          predicates:
            - Path=/api/config/**

        - id: jira-service-route
          uri: lb://JIRA-SERVICE
          predicates:
            - Path=/api/jira/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "gateway,health,info,prometheus"

logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.gateway.filter.LoadBalancerClientFilter: TRACE