spring:
  datasource:
    url: jdbc:postgresql://${SERVER_IP}:5432/auth_db
    username: postgres
    password: secret
    hikari:
      connection-init-sql: "SET TIME ZONE 'UTC'"
      maximum-pool-size: 3
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true

  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [traceId=%X{traceId},spanId=%X{spanId}]"

  level:
    root: INFO
    com.incidentbbrain.alertservice: INFO
    org.springframework.web: INFO

server:
  port: 8090