spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: secret
    hikari:
      connection-init-sql: "SET TIME ZONE 'UTC'"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8090