server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://${SERVER_IP}:5432/jira_db
    username: postgres
    password: secret

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${SERVER_IP}:9092
    consumer:
      group-id: jira-orchestrator-group
      auto-offset-reset: earliest

  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

  eureka:
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${random.uuid}

encryption:
  master-key: ${ENCRYPTION_MASTER_KEY}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

  endpoint:
    health:
      show-details: always

  metrics:
    export:
      prometheus:
        enabled: true

  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [traceId=%X{traceId},spanId=%X{spanId}]"

  level:
    root: INFO
    com.incidentbbrain.alertservice: INFO
    org.springframework.web: INFO