spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Use the absolute path to your config folder
          search-locations: file:///C:/Users/Mahesh Yadav/Desktop/IncidentBrain/infrastructure/config-service/src/main/resources/config/

server:
  port: 8888