server:
  port: 8083

spring:
  application:
    name: context-service

  # --- DATABASE CONFIGURATION (Postgres) ---
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/incident_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Automatically creates tables (enriched_incidents)
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # --- KAFKA CONFIGURATION ---
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: context-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.incidentbbrain.incidentbraincommon.common,com.incidentbbrain.contextservice.dto"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.incidentbbrain.incidentbraincommon.common.IncidentEvent

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

context:
  kafka:
    topics:
      incidents-created: incidents.created
      context-ready: context.ready

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.incidentbbrain.contextservice: DEBUG
    org.hibernate.SQL: DEBUG # Useful for debugging DB inserts
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"